//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityJournal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Lesson_ID { get; set; }
        public string Day_of_week { get; set; }
        public int LessonNo { get; set; }
        public string Group_Name { get; set; }
        public string Subject_Name { get; set; }
        public string Teacher { get; set; }
    }
}
