//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityJournal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class University_Schedule
    {
        public University_Schedule()
        {
            this.University_StudentPresence = new HashSet<University_StudentPresence>();
        }
    
        public int Lesson_ID { get; set; }
        public string Day_of_week { get; set; }
        public int LessonNo { get; set; }
        public int Group_ID { get; set; }
        public int Teacher_ID { get; set; }
        public int Subject_ID { get; set; }
    
        public virtual University_Group University_Group { get; set; }
        public virtual University_Subject University_Subject { get; set; }
        public virtual University_Teacher University_Teacher { get; set; }
        public virtual ICollection<University_StudentPresence> University_StudentPresence { get; set; }
    }
}
