//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityJournal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class University_Subject
    {
        public University_Subject()
        {
            this.University_Schedule = new HashSet<University_Schedule>();
            this.University_Group = new HashSet<University_Group>();
            this.University_Teacher = new HashSet<University_Teacher>();
        }
    
        public int Subject_ID { get; set; }
        public string Subject_Name { get; set; }
    
        public virtual ICollection<University_Schedule> University_Schedule { get; set; }
        public virtual ICollection<University_Group> University_Group { get; set; }
        public virtual ICollection<University_Teacher> University_Teacher { get; set; }
    }
}
