//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityJournal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_StudentPresence
    {
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public bool Present { get; set; }
        public Nullable<int> Mark { get; set; }
        public int LessonID { get; set; }
        public System.DateTime Date { get; set; }
        public int Group_ID { get; set; }
    }
}
